JSONSting issue
saleor/saleor pull request #10124
Opened 2022-07-08 13:59 UTC by sanket-jethava

We are not return the graphene.JSONStirng.parse_literal from fields.py of graphql core. Due to this we are unable to run take input of CategoryInput, CollectionInput and CategoryInput. So now we are add return startement and now we will able to run it properly.

Please accept the changes. Many users like me will not more facing issues of JSONString field.

Thanks!

I want to merge this change because...

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-07-11 08:47 UTC, korycins approved these changes

2022-07-12 09:28 UTC, maarcingebala commented
Hey @sanket-jethava, thanks for opening the PR. Can you only keep the changes related to JSONString issue? I would skip the email plugin changes and if we want to add them, open a separate PR with description of these changes.

2022-07-12 09:32 UTC, korycins requested changes
- I don't think that changes in the email plugins should be the scope of this PR
-

2022-07-12 09:32 UTC, korycins commented on saleor/plugins/user_email/plugin.py
> +            host=configuration["host"] or settings.EMAIL_HOST,
I don't think that this is the expected way of handling this. 
This is a plugin that should be configured from the dashboard. Only the Admin plugin needs to have a configuration from settings.

2022-07-12 10:48 UTC, sanket-jethava commented
> Hey @sanket-jethava, thanks for opening the PR. Can you only keep the changes related to JSONString issue? I would skip the email plugin changes and if we want to add them, open a separate PR with description of these changes.

Yes, Sure. I will open a seperate PR for the same.

Thanks for verify and quick response.

2022-07-12 11:12 UTC, korycins commented
Hey @sanket-jethava you removed a whole file: `saleor/plugins/user_email/plugin.py`. I don't think that this is expected. Let's revert it to a form as it was previously.

2022-07-12 11:59 UTC, sanket-jethava commented
> your

@maarcingebala, I think it's done now. please review it.

Thanks!

2022-07-12 12:03 UTC, maarcingebala commented
There is still some irrelevant change in this file: 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/5421321/178485545-11397462-60e3-4af9-b0af-556808ab2e68.png">
Please revert all changes and keep only the one related to JSONString.

2022-07-12 12:11 UTC, sanket-jethava commented
@maarcingebala please verify. I have made changes as you said.

Thanks for quick response and support!

2022-07-12 12:37 UTC, maarcingebala approved these changes

2022-07-12 12:40 UTC, korycins approved these changes

2022-07-12 13:10 UTC, sanket-jethava commented
@maarcingebala and @korycins Thank you for approve pull request!

2022-07-12 13:12 UTC, merged

2022-07-12 13:12 UTC, maarcingebala commented
Thanks for contributing to Saleor @sanket-jethava!