Optimize filtering attributes by dates
saleor/saleor pull request #10199
Opened 2022-07-20 07:18 UTC by tomaszszymanski129

I want to merge this change because it optimizes filtering attributes by dates.

local DB (nearly 2M attr values)

Before: 9.87s ❌ 
After: 130ms ✔️ 

Also significantly lowers the returned count of the rows from database as the filtering is now happening on the database layer and more rows are discarded before even being processed by python.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-07-20 07:18 UTC, patrys commented
Task linked: [CLOUD-1782 Investigate slow attribute filtering on RT dev](https://app.clickup.com/t/2549495/CLOUD-1782)

2022-07-25 07:32 UTC, maarcingebala approved these changes

2022-07-25 07:37 UTC, IKarbowiak requested changes

2022-07-25 07:37 UTC, IKarbowiak commented on saleor/graphql/product/tests/test_product.py
> +    date_value = datetime.utcnow()
It adds warnings to tests. It must have tzinfo.

2022-07-25 07:57 UTC, korycins approved these changes

2022-07-25 09:05 UTC, IKarbowiak approved these changes

2022-07-26 07:23 UTC, merged