Add filter by slug
saleor/saleor pull request #10578
Opened 2022-09-07 15:18 UTC by kadewu

Adding possibility to filter by slug, to endpoints:
- products
- collections
- categories
- pages

Issue [9476](https://github.com/saleor/saleor/issues/9476)

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-09-07 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saleor/saleor?pullRequest=10578) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saleor/saleor?pullRequest=10578) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saleor/saleor?pullRequest=10578) it.</sub>

2022-09-08 12:38 UTC, fowczarek approved these changes

2022-09-12 08:00 UTC, maarcingebala approved these changes

2022-09-12 08:11 UTC, maarcingebala requested changes
@kadewu There are more types that support `slug: String` and I think we should add this filter as well to queries for these types, to make it consistent:

Warehouse.slug: String!
Channel.slug: String!
ProductType.slug: String!
Attribute.slug: String
AttributeValue.slug: String
AttributeInput.slug: String!
PageType.slug: String!
Menu.slug: String!

Also, please update the changelog to mention this change and list which GraphQL types were changed.

2022-09-15 07:42 UTC, kadewu commented
> @kadewu There are more types that support `slug: String` and I think we should add this filter as well to queries for these types, to make it consistent:
> 
> Warehouse.slug: String! Channel.slug: String! ProductType.slug: String! Attribute.slug: String AttributeValue.slug: String AttributeInput.slug: String! PageType.slug: String! Menu.slug: String!
> 
> Also, please update the changelog to mention this change and list which GraphQL types were changed.

What about menu query? There is slug filter already implemented, I added slugs, to make it consistent, should we mark old one as deprecated, or do not add slugs here?

2022-09-15 10:48 UTC, maarcingebala approved these changes

2022-09-15 10:49 UTC, merged