Add new filters to products
saleor/saleor pull request #10784
Opened 2022-09-30 08:26 UTC by kadewu

Add filters:
- isAvailable
- publishedFrom
- availableFrom
- listed

Fix [10370](https://github.com/saleor/saleor/issues/10370)

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-10-06 08:19 UTC, IKarbowiak commented on saleor/graphql/product/filters.py
> +    channel = Channel.objects.filter(slug=channel_slug).values("pk")
You should handle the empty value here too. And please add test for this scenario

2022-10-06 08:42 UTC, kadewu commented on saleor/graphql/product/filters.py
> +    listed = django_filters.BooleanFilter(
I also wasn't sure about the name, so just followed the suggestion from issue. I like the proposal to change it though.

2022-10-07 14:02 UTC, kadewu commented on saleor/graphql/product/filters.py
> +    if value:
I've just started applying changes, but after some thought I wonder if should I actually care about `None`. I mean, the `None` value is handled in `field`, so the `None` will never be passed here, and I've marked those methods as private. I can of course add that logic here for the future, but then I would need to introduce tests on 'private' method.

2022-10-10 07:35 UTC, IKarbowiak commented on saleor/graphql/product/filters.py
> +    if value:
Yep, you are right, I checked the call with providing `null` as boolean filter value and it didn't enter the method.

2022-10-10 07:37 UTC, IKarbowiak approved these changes

2022-10-10 08:34 UTC, maarcingebala reviewed
I've redacted the descriptions slightly to make them more docs-friendly.

2022-10-10 08:34 UTC, maarcingebala commented on saleor/graphql/product/filters.py
> +        help_text=f"Filter by published from date. {ADDED_IN_38}",
```suggestion
        help_text=f"Filter by the publication date. {ADDED_IN_38}",
```

2022-10-10 08:34 UTC, maarcingebala commented on saleor/graphql/product/filters.py
> +        help_text=f"Filter by available for purchase. {ADDED_IN_38}",
```suggestion
        help_text=f"Filter by availability for purchase. {ADDED_IN_38}",
```

2022-10-10 08:34 UTC, maarcingebala commented on saleor/graphql/product/filters.py
> +        help_text=f"Filter by visible in product listings. {ADDED_IN_38}",
```suggestion
        help_text=f"Filter by visibility in product listings. {ADDED_IN_38}",
```

2022-10-10 08:34 UTC, maarcingebala commented on saleor/graphql/product/filters.py
> +        help_text=f"Filter by available for purchase from date. {ADDED_IN_38}",
```suggestion
        help_text=f"Filter by the date of availability for purchase. {ADDED_IN_38}",
```

2022-10-10 10:38 UTC, fowczarek approved these changes

2022-10-10 13:00 UTC, maarcingebala approved these changes

2022-10-13 13:01 UTC, eCzerniak requested changes
![image](https://user-images.githubusercontent.com/29308910/195602152-5e136745-9cbb-41be-9c47-df56844a4917.png)

`publishedFrom` and `availableFrom` are not working as they should. When I am using those filters then I get products whit different date then I choose.

2022-10-13 16:07 UTC, kadewu commented
> ![image](https://user-images.githubusercontent.com/29308910/195602152-5e136745-9cbb-41be-9c47-df56844a4917.png)
> 
> `publishedFrom` and `availableFrom` are not working as they should. When I am using those filters then I get products whit different date then I choose.

Maybe I should change or better explain the description on those two filters. I believe that they work fine cause the idea is, to check if the `product` will be for example available in future. So if the date `availableAt` is smaller than what we asked for, then that means `product` is available.

2022-10-17 11:14 UTC, eCzerniak approved these changes

2022-10-18 07:54 UTC, merged