Do not require email when adding voucher to checkout
saleor/saleor pull request #10853
Opened 2022-10-07 08:49 UTC by kadewu

Fix https://github.com/saleor/saleor/issues/10823

This pull request removes email validation from adding the promo code to checkout.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-10-07 09:33 UTC, maarcingebala approved these changes

2022-10-11 06:38 UTC, IKarbowiak requested changes
This validation was added as this mutation is also used for adding the gift cards, and gift card validation required the email address. If we remove this condition, we will break the gift card assumptions.

2022-10-11 06:41 UTC, IKarbowiak commented
I think we may validate the checkout email only when gift card code is given.

2022-10-11 07:17 UTC, maarcingebala commented
Then we should also add some comments in code around this email validation, as it may not be obvious that it's required for gift card assumptions.

2022-10-11 07:38 UTC, IKarbowiak commented
It seems like we can move this validation to `add_gift_card_code_to_checkout`and then it will be obvious

2022-10-11 07:42 UTC, maarcingebala commented
Yep that's a good idea 👍

2022-10-13 13:47 UTC, eCzerniak commented
Please add QA when it will be ready to test.

2022-10-20 07:29 UTC, maarcingebala approved these changes

2022-10-26 05:55 UTC, fowczarek approved these changes

2022-10-26 10:35 UTC, szczecha approved these changes

2022-10-26 10:44 UTC, merged