Sorting by `created_at` field for multiple queries
saleor/saleor pull request #10911
Opened 2022-10-12 18:07 UTC by zedzior

I want to merge this change, because I want to enable sorting by `created_at` field for all the queries, which are ran behind dashboard's tables. This PR adds the sorting to `giftCards`, `pages` and `vouchers` queries. 

Issue: https://github.com/saleor/saleor/issues/10907

# Impact

* [ ] New migrations
* [x] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-10-13 10:16 UTC, zedzior commented on saleor/graphql/schema.graphql
> +  DEPRECATED: this field will be removed in Saleor 4.0.
`npm run build-schema` command created wrong schema: it should say `Added in Saleor 3.8.` 
```
if self.name == "CREATION_DATE":
    description += DEPRECATED_IN_3X_INPUT
if self.name == "CREATED_AT":
    description += ADDED_IN_38
```
Same issue above for `PUBLISHED_AT`. It looks like, whenever a sorter is exactly the same, but different named, the problem occurs. Is it a known drawback of the `npm run build-schema` command?

2022-10-18 13:41 UTC, IKarbowiak approved these changes

2022-10-19 17:34 UTC, NyanKiyoshi requested changes

2022-10-19 17:34 UTC, NyanKiyoshi commented on saleor/graphql/giftcard/sorters.py
> +            return description
There is no index:
https://github.com/saleor/saleor/blob/c28b12323141208257338c3619a57bd2dc8b1922/saleor/giftcard/models.py#L70

2022-10-19 17:34 UTC, NyanKiyoshi commented on saleor/graphql/page/sorters.py
> +                description += ADDED_IN_38
There is no index:
https://github.com/saleor/saleor/blob/c28b12323141208257338c3619a57bd2dc8b1922/saleor/page/models.py#L26

2022-10-19 17:34 UTC, NyanKiyoshi commented on saleor/graphql/page/sorters.py
> +                description += DEPRECATED_IN_3X_INPUT
Does that make sense to introduce a new filter and instantly deprecate it? Why not only introduce the non-deprecated one?

2022-10-20 08:01 UTC, zedzior commented on saleor/graphql/schema.graphql
> +  DEPRECATED: this field will be removed in Saleor 4.0.
Going to be fixed in separate PR (https://github.com/saleor/saleor/issues/10968)

2022-10-21 09:49 UTC, fowczarek approved these changes

2022-10-24 08:57 UTC, merged