Order app structure improvement
saleor/saleor pull request #11226
Opened 2022-11-17 09:08 UTC by zedzior

I want to merge this change because currently tests in order app are messy and need to be restructured.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-11-17 10:16 UTC, IKarbowiak requested changes

2022-11-17 10:16 UTC, IKarbowiak commented on saleor/graphql/order/tests/mutations/test_fulfillment.py
> +from saleor.warehouse.models import Allocation, Stock
We are using relative imports 👮‍♀️

2022-11-17 10:52 UTC, fowczarek commented on saleor/graphql/order/tests/mutations/test_draft_order_bulk_delete.py
> +from saleor.order import models as order_models
We use relative import in other test files. This takes place in several other files.
IMO we should use the same import type in all tests.

2022-11-23 08:16 UTC, fowczarek approved these changes

2022-11-24 08:18 UTC, IKarbowiak approved these changes

2022-11-28 12:22 UTC, merged