Deactivate webhook before deleting
saleor/saleor pull request #11239
Opened 2022-11-18 12:22 UTC by jakubkuc

I want to merge this change because it prevents issue where using `WebhookDelete` mutation while tasks that create `EventDeliveryAttempt` are queued resulted in `IntegrityError`.

The most simple resolution was to deactivate Webhook before deleting it in mutation. `send_webhook_request_async` task is checking if webhook `is_active` so this should prevent this situation.
Tasks

Things to discuss: 
⚠️ There is a small window for this solution to fail - when Webhook deactivation will happen between the `is_active` check and attempt creating/updating in `send_webhook_request_async` task. I'm not quite sure how to handle this case. Should I add more webhook activity checks inside `send_webhook_request_async` task or maybe catch this edge-case exception to fail gracefully?  Any ideas? 

#11227 
# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-11-21 10:12 UTC, SzymJ approved these changes

2022-11-21 10:22 UTC, przlada requested changes

2022-11-21 10:22 UTC, przlada commented on saleor/graphql/webhook/mutations.py
> +        except IntegrityError:
You are only deactivating the webhook if the delete mutation comes from an app, not the user

2022-11-23 07:38 UTC, korycins commented on saleor/graphql/webhook/tests/test_webhook.py
> +def test_webhook_delete_deactivates_before_deletion(
Wouldn't be good to have a separate test, that will check that ValidationError has been raised?

2022-11-23 07:39 UTC, korycins commented on saleor/graphql/webhook/mutations.py
> +            webhook = webhook or models.Webhook.objects.get(object_id)
WDYT?

2022-11-25 12:28 UTC, jakubkuc commented on saleor/graphql/webhook/mutations.py
> +            webhook = webhook or models.Webhook.objects.get(object_id)
Brilliant, I'll test it

2022-11-28 08:37 UTC, jakubkuc commented on saleor/graphql/webhook/mutations.py
> +                code=WebhookErrorCode.GRAPHQL_ERROR,
Good point. I'll add a new code. Maybe `DELETE_FAILED`?

2022-11-28 09:37 UTC, jakubkuc commented on saleor/graphql/webhook/mutations.py
> +            webhook = webhook or models.Webhook.objects.get(object_id)
Works well. I've updated the PR 🚀

2022-11-28 10:13 UTC, fowczarek approved these changes

2022-12-06 14:06 UTC, przlada approved these changes

2022-12-09 10:24 UTC, maarcingebala reviewed
We need to update the description of `webhookDelete` mutation to explain that the deletion might fail if there is a webhook delivery in progress, but webhooks get deactivated in that case.

2022-12-09 10:24 UTC, maarcingebala commented on saleor/graphql/webhook/mutations.py
> +                f"Couldn't resolve to a node: {webhook.app.id}",
We should return GraphQL node ID, but `webhook.app.id` is a database ID. Also before it was returning the ID of the webhook, not the app.

2022-12-09 10:24 UTC, maarcingebala commented on saleor/graphql/webhook/mutations.py
> +        if app and webhook.app.id != app.id:
Doesn't `webhook.app.id` make a database query? Could be `webhook.app_id` instead I guess.

2022-12-13 10:40 UTC, closed without merging