Add release issue template
saleor/saleor pull request #13256
Opened 2023-06-30 14:04 UTC by maarcingebala

This template will be used to create issues where we'll be tracking progress on new minor releases of Saleor.

2023-06-30 14:07 UTC, andrzejewsky approved these changes

2023-06-30 15:32 UTC, patrys commented on .github/ISSUE_TEMPLATE/release.md
> +- [ ] Inform about stable release (sandbox) - @czarek
Which handle is correct?

2023-06-30 15:34 UTC, maarcingebala commented on .github/ISSUE_TEMPLATE/release.md
> +- [ ] Inform about stable release (sandbox) - @czarek
fixed

2023-07-03 06:35 UTC, korycins commented
It is only a detail but Is it okay that you rely on a specific person? What if you will be off or something? Shouldn't we have here assigned groups? Even if this will be single person group.

2023-07-03 07:29 UTC, maarcingebala commented
@korycins We don't want to ping entire teams, only responsible people. If they'll be off/unavailable, we'll agree on who's replacing them and change them in the task.

2023-07-03 07:34 UTC, IKarbowiak commented on .github/ISSUE_TEMPLATE/release.md
> +- [ ] inform about alpha tag - @andrzejewsky
🚔 
```suggestion
- [ ] Inform about alpha tag - @andrzejewsky
```

2023-07-03 09:58 UTC, andrzejewsky requested changes

2023-07-03 09:58 UTC, andrzejewsky commented on .github/ISSUE_TEMPLATE/release.md
> +- [ ] Inform about finished deployment on slack channel - @cmiacz
```suggestion
- [ ] Inform about finished deployment - @cmiacz
```

2023-07-04 07:54 UTC, andrzejewsky approved these changes

2023-07-04 08:42 UTC, IKarbowiak approved these changes

2023-07-04 08:56 UTC, merged