Add permission checking based on Attribute.type
saleor/saleor pull request #13493
Opened 2023-07-21 14:41 UTC by 8r2y5

I want to merge this change because adds validation if user has permissions to create/update/delete AttributeValue based on Attribute.type.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migrations are either absent or optimized for zero downtime
* [ ] The changes are covered by test cases

2023-07-24 09:03 UTC, IKarbowiak commented on saleor/tests/fixtures.py
> +    )
Do we need these new fixtures? We already have `page_type` examples of attributes: `size_page_attribute`, `tag_page_attribute, `author_page_attribute`

2023-07-24 10:33 UTC, SzymJ approved these changes

2023-07-24 10:35 UTC, fowczarek requested changes
This PR makes AttrubuteValues permission less clear. 
Before you PR we required `MANAGE_PRODUCTS` for `AttributeValueCreate` and `MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES` for `AttributeValueUpdate` \ `AttributeValueDelete`. 

After your PR:
1. `AttributeValueCreate` mutation
1.1  Required permissions:
- `MANAGE_PRODUCTS` for product attributes
- `MANAGE_PRODUCTS` and `MANAGE_PAGES` for page attributes
1.2. Description mutation has info that only `MANAGE_PRODUCTS` is required
1.3  We perform 2nd separate permission validation.  If the staff user misses both permissions they receive the error message that only `MANAGE_PRODUCTS`. When I add `MANAGE_PRODUCTS` to current use the staff starts receiving another validation error that `MANAGE_PAGES` is required.
2. `AttributeValueUpdate` \`AttributeValueDelete` 
2.1  Required permissions:
- `MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES ` and `MANAGE_PRODUCTS ` for product attributes
- `MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES ` and `MANAGE_PAGES` for page attributes
2.2 Description mutation has info that only `MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES` is required
2.3 We perform 2nd separate permission validation. If the staff user misses both permissions they receive the error message that only `MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES`. When I add `MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES` to current use the staff starts receiving another validation error that `MANAGE_PAGES` is required.

3. Why don't you add a new test to successfully create/update/delete AttributesValues for page attributes with minimal permissions?

2023-08-09 12:00 UTC, 8r2y5 commented
Refactor of those changes https://github.com/saleor/saleor/pull/13650

2023-08-09 12:00 UTC, closed without merging