Refactor sale create mutation
saleor/saleor pull request #13624
Opened 2023-08-04 11:57 UTC by zedzior

I want to merge this change, because it makes `saleCreate` mutation compatible with new Promotion model.

This PR also corrects `sale_converter` and `0049_migrate_sales_to_promotions` , to return empty predicate instead of `{"OR": []}` for old sales without catalogue.

Promotions created by the mutation must be treated as "old sale", therefor `old_sale_id` is assigned.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migrations are either absent or optimized for zero downtime
* [ ] The changes are covered by test cases

2023-08-08 08:43 UTC, SzymJ approved these changes

2023-08-09 09:51 UTC, IKarbowiak requested changes

2023-08-09 09:51 UTC, IKarbowiak commented on saleor/discount/migrations/0050_old_sale_id_sequence.py
> +                 coalesce(max(old_sale_id), 0) + 1, false
IMO it should be more than + 1 as the new sales might be created it meantime

2023-08-09 12:23 UTC, IKarbowiak approved these changes

2023-08-09 12:58 UTC, merged