[TEST] Should be able to create partially paid order CORE_0112
saleor/saleor pull request #13631
Opened 2023-08-07 08:54 UTC by szczecha

I want to merge this change because it adds a test for creating partially paid orders CORE_0112

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migrations are either absent or optimized for zero downtime
* [ ] The changes are covered by test cases

2023-08-14 07:37 UTC, IKarbowiak approved these changes

2023-08-14 10:51 UTC, yellowee requested changes

2023-08-14 10:51 UTC, yellowee commented on saleor/tests/e2e/transactions/utils.py
> +    amount=1,
I would suggest to create a separate functions for fully paid and partially paid order. Alternatively I would add the variable `amount` in your test as currently you use create_transaction(api_client, id) without providing the amount for a partial payment. IMO it's confusing and not clear as a person who reads the test code have to go to utils to ensure the insufficient value was used for the payment.

2023-08-14 13:39 UTC, yellowee approved these changes

2023-08-16 10:13 UTC, fowczarek approved these changes

2023-08-16 10:28 UTC, merged