[TEST] adding test for order with invalid shipping method CORE 0203
saleor/saleor pull request #13864
Opened 2023-09-04 09:22 UTC by yellowee

I want to merge this change because it covers TC CORE 0203

# Impact

- [ ] New migrations
- [ ] New/Updated API fields or mutations
- [ ] Deprecated API fields or mutations
- [ ] Removed API types, fields, or mutations

# Docs

- [ ] Link to documentation:

# Pull Request Checklist

- [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
- [ ] Database queries are optimized and the number of queries is constant
- [ ] Database migrations are either absent or optimized for zero downtime
- [ ] The changes are covered by test cases

2023-09-04 10:06 UTC, szczecha requested changes
The steps in the test do not match those from Testmo. For this case, changing the address after selecting the shipping method and verifying the error message if someone tries to complete the order is crucial.

2023-09-05 08:23 UTC, szczecha commented on saleor/tests/e2e/orders/test_cannot_fullfill_order_with_invalid_shipping_method.py
> +    second_warehouse_data = create_warehouse(
One warehouse is enough. You need to have two separate shipping methods for different countries.

2023-09-05 08:23 UTC, szczecha commented on saleor/tests/e2e/orders/test_cannot_fullfill_order_with_invalid_shipping_method.py
> +
Can you add an extra check for available shipping methods? To make sure that after changing address the shipping methods list contains now the shipping method ID for the PL address.

2023-09-05 12:58 UTC, fowczarek approved these changes

2023-09-06 12:17 UTC, szczecha approved these changes

2023-09-06 12:17 UTC, merged