[TEST] Create order in channel with transaction flow as mark as paid strategy CORE_0209
saleor/saleor pull request #13954
Opened 2023-09-12 08:56 UTC by yellowee

I want to merge this change because it checks adding an order with transaction flow as mark as paid channel's strategy [CORE_0209](https://saleor.testmo.net/repositories/5?group_id=112&case_id=2379)

# Impact

- [ ] New migrations
- [ ] New/Updated API fields or mutations
- [ ] Deprecated API fields or mutations
- [ ] Removed API types, fields, or mutations

# Docs

- [ ] Link to documentation:

# Pull Request Checklist

- [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
- [ ] Database queries are optimized and the number of queries is constant
- [ ] Database migrations are either absent or optimized for zero downtime
- [ ] The changes are covered by test cases

2023-09-12 11:21 UTC, 8r2y5 approved these changes

2023-09-12 11:52 UTC, szczecha requested changes

2023-09-12 11:52 UTC, szczecha commented on saleor/tests/e2e/orders/test_order_in_channel_with_transaction_flow_as_mark_as_paid_strategy.py
> +    )
For making an order as paid in transaction flow you need to run a mutation orderMarkAsPaid with transaction reference and then check if the created order.transactions is not empty.
```
mutation OrderMarkAsPaid($id: ID!, $transactionReference: String) {
  orderMarkAsPaid(id: $id, transactionReference: $transactionReference) {
    errors {
      code
    }
    order {
      id
    }
  }
}



{
  "id": "id",
  "transactionReference": "test-pspreference"
}
```

2023-09-15 06:32 UTC, szczecha commented on saleor/tests/e2e/orders/test_order_in_channel_with_transaction_flow_as_mark_as_paid_strategy.py
> +    # Step 5 - Mark order as paid in transaction flow and check order's payment status
Please can you add extra check that order.transactions is not empty?

2023-09-15 08:33 UTC, szczecha commented on saleor/tests/e2e/orders/test_order_in_channel_with_transaction_flow_as_mark_as_paid_strategy.py
> +        _,
use variable name

2023-09-15 09:05 UTC, IKarbowiak approved these changes

2023-09-15 09:07 UTC, szczecha approved these changes

2023-09-15 10:33 UTC, merged