[Test] Should be able to create variants in bulk
saleor/saleor pull request #13995
Opened 2023-09-18 11:26 UTC by szczecha

I want to merge this change because it adds a test for creating products in bulk [CORE_0301](https://saleor.testmo.net/repositories/5?group_id=111&case_id=750)

# Impact

- [ ] New migrations
- [ ] New/Updated API fields or mutations
- [ ] Deprecated API fields or mutations
- [ ] Removed API types, fields, or mutations

# Docs

- [ ] Link to documentation:

# Pull Request Checklist

- [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
- [ ] Database queries are optimized and the number of queries is constant
- [ ] Database migrations are either absent or optimized for zero downtime
- [ ] The changes are covered by test cases

2023-09-18 12:25 UTC, yellowee requested changes

2023-09-18 12:25 UTC, yellowee commented on saleor/tests/e2e/attributes/utils/create_attribute.py
> +    e2e_not_logged_api_client,
Change to `api.client` please

2023-09-18 12:25 UTC, yellowee commented on saleor/tests/e2e/product/utils/product_query.py
> +    staff_api_client,
`api.client` - Same here since not only staff should be able to get product info

2023-09-18 12:55 UTC, yellowee approved these changes

2023-09-19 06:57 UTC, IKarbowiak approved these changes

2023-09-19 07:59 UTC, merged