[TEST] Promotions query with different params CORE_2118
saleor/saleor pull request #14132
Opened 2023-09-29 09:58 UTC by yellowee

I want to merge this change because it covers [TC CORE_2118](https://saleor.testmo.net/repositories/5?group_id=133&case_id=2354) - quering promotions with various parameters.

# Impact

- [ ] New migrations
- [ ] New/Updated API fields or mutations
- [ ] Deprecated API fields or mutations
- [ ] Removed API types, fields, or mutations

# Docs

- [ ] Link to documentation:

# Pull Request Checklist

- [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
- [ ] Database queries are optimized and the number of queries is constant
- [ ] Database migrations are either absent or optimized for zero downtime
- [ ] The changes are covered by test cases

2023-09-29 10:49 UTC, szczecha commented on saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
> +    promotions_list = promotions_query(e2e_staff_api_client, first=10)
I know that by default we sort by DESC but for the purpose of this test can you add parameter `sort_by={"field": "CREATED_AT", "direction": "DESC"},`

2023-09-29 11:06 UTC, szczecha approved these changes

2023-10-02 06:18 UTC, IKarbowiak requested changes

2023-10-02 06:18 UTC, IKarbowiak commented on saleor/tests/e2e/promotions/test_promotions_query_with_different_parameters.py
In each of those tests you should also create the promotion that do not match the filtering conditions, to ensure that the filter working correctly and not returning all promotions each time

2023-10-04 06:51 UTC, IKarbowiak approved these changes

2023-10-04 14:31 UTC, merged