Add voucher to checkout query.
saleor/saleor pull request #14512
Opened 2023-10-29 16:54 UTC by zedzior

I want to merge this change, because it add `voucher` field to `checkout` query.

# Impact

- [ ] New migrations
- [X] New/Updated API fields or mutations
- [ ] Deprecated API fields or mutations
- [ ] Removed API types, fields, or mutations

# Docs

- [ ] Link to documentation:

# Pull Request Checklist

- [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
- [ ] Database queries are optimized and the number of queries is constant
- [ ] Database migrations are either absent or optimized for zero downtime
- [ ] The changes are covered by test cases

2023-10-30 07:39 UTC, korycins commented on saleor/graphql/checkout/types.py
> +        description="The voucher assigned to the checkout.",
Shouldn't be ADDED_IN here?

2023-10-30 11:37 UTC, IKarbowiak commented on saleor/graphql/checkout/types.py
> +from ..discount.dataloaders import VoucherByCodeLoader
I cannot find such dataloader in this file
https://github.com/saleor/saleor/blob/add-voucher-to-checkout-query/saleor/graphql/discount/dataloaders.py

2023-10-31 12:03 UTC, SzymJ approved these changes

2023-10-31 12:26 UTC, IKarbowiak requested changes

2023-10-31 12:26 UTC, IKarbowiak commented on saleor/graphql/discount/dataloaders.py
> +            return vouchers
In such case you are not ensuring that the returned vouchers are in the same order as keys.
You must ensure that in the index 1 of vouchers I will find the voucher for code provided on index 1 in keys.

2023-10-31 12:26 UTC, IKarbowiak commented on saleor/graphql/discount/dataloaders.py
> +            return vouchers
And you should also create a test with multiple vouchers that will catch such mismatch

2023-11-02 09:29 UTC, korycins approved these changes

2023-11-02 10:13 UTC, IKarbowiak approved these changes

2023-11-02 12:28 UTC, yellowee approved these changes

2023-11-02 12:36 UTC, merged