add `taxConfiguration` to `Channel` for tax app calculation precision.
saleor/saleor pull request #15610
Opened 2024-03-15 12:32 UTC by Air-t

sion.

I want to merge this change because...

# Impact

- [ ] New migrations
- [ ] New/Updated API fields or mutations
- [ ] Deprecated API fields or mutations
- [ ] Removed API types, fields, or mutations

# Docs

- [ ] Link to documentation:

# Pull Request Checklist

- [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
- [ ] Database queries are optimized and the number of queries is constant
- [ ] Database migrations are either absent or optimized for zero downtime
- [ ] The changes are covered by test cases
- [ ] All new fields/inputs/mutations have proper labels added (`ADDED_IN_X`, `PREVIEW_FEATURE`, etc.)
- [ ] All migrations have proper dependencies
- [ ] All indexes are added concurrently in migrations
- [ ] All RunSql and RunPython migrations have revert option defined

2024-03-18 11:06 UTC, tomaszszymanski129 requested changes

2024-03-18 11:06 UTC, tomaszszymanski129 commented on saleor/settings.py
> +JWT_EXPIRE = False
Nope.

2024-03-20 07:08 UTC, Air-t commented on saleor/graphql/channel/types.py
> +        required=False,
you are right, I will change it, otherwise, we will need to mark it as a breaking change

2024-03-20 09:47 UTC, tomaszszymanski129 approved these changes

2024-03-21 06:56 UTC, merged