Improve product search
saleor/saleor pull request #8734
Opened 2021-12-06 12:12 UTC by IKarbowiak

- Introduce `search_document` product field, that collect values from all fields used in searching
- Drop `search_vector` field and related triggers
- Add index for `search_document` product field
- Update `search_document` whenever any of the fields are changed
- Make search case insensitive
- Update random data - generate search value for created products

Explain (5000 products):
https://explain.dalibo.com/plan/c4K

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2021-12-06 12:12 UTC, patrys commented
Task linked: [SALEOR-4920 Search by text attribute](https://app.clickup.com/t/2549495/SALEOR-4920)

2021-12-07 09:14 UTC, fowczarek approved these changes

2021-12-15 10:34 UTC, tomaszszymanski129 requested changes

2021-12-15 10:34 UTC, tomaszszymanski129 commented on saleor/core/search_tasks.py
> +    )[:BATCH_SIZE]
⚠️ shouldn't this be iterated over in batches instead of limiting it to batch size?

2021-12-15 10:34 UTC, tomaszszymanski129 commented on saleor/graphql/attribute/bulk_mutations.py
> +            Exists(Exists(assigned_variant_attrs.filter(variant_id=OuterRef("id"))))
double exists?

2021-12-15 11:14 UTC, maarcingebala approved these changes

2021-12-15 13:07 UTC, tomaszszymanski129 approved these changes

2021-12-27 12:29 UTC, NyanKiyoshi commented on saleor/settings.py
> +CELERY_TASK_ALWAYS_EAGER = False
Looks like an accidental change

2021-12-27 12:36 UTC, IKarbowiak commented on saleor/settings.py
> +CELERY_TASK_ALWAYS_EAGER = False
True. Thanks

2021-12-28 07:48 UTC, maarcingebala commented on saleor/product/migrations/0157_update_product_search_document.py
> +        ("product", "0156_product_sarch_document"),
Typo in migration name.

2022-01-05 09:15 UTC, tomaszszymanski129 approved these changes

2022-01-05 09:19 UTC, merged