Make collection name non-unique
saleor/saleor pull request #8986
Opened 2022-01-20 17:53 UTC by rafalp

Makes collection name non-unique (just like it is for pages)

# Impact

* [x] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [x] Database migration files are up to date
* [ ] The changes are tested
* [x] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2022-01-20 17:53 UTC, patrys commented
Task linked: [SALEOR-5690 Make collection name non unique](https://app.clickup.com/t/2549495/SALEOR-5690)

2022-01-21 05:41 UTC, L3str4nge approved these changes

2022-01-21 08:16 UTC, IKarbowiak approved these changes

2022-01-24 07:57 UTC, tomaszszymanski129 approved these changes

2022-01-24 10:19 UTC, maarcingebala reviewed
If I recall correctly we should also rework `CollectionSortField`:
```
class CollectionSortField(graphene.Enum):
    NAME = ["name"]
    AVAILABILITY = ["is_published", "name"]
    PRODUCT_COUNT = ["product_count", "name"]
    PUBLICATION_DATE = ["publication_date", "name"]
```
Each sorting option is constructed as a list of model fields where the last field must be a unique one. Since name won't be unique anymore we should change it to `pk`.

2022-01-24 10:43 UTC, maarcingebala requested changes
Update the `CollectionSortField`.

2022-01-25 11:09 UTC, maarcingebala approved these changes

2022-01-26 08:54 UTC, merged