Optimize assign_quantity_allocated_to_stocks to work in batches
saleor/saleor pull request #9235
Opened 2022-02-23 17:00 UTC by tomaszszymanski129

I want to merge this change because it optimizes assign_quantity_allocated_to_stocks migration func to work in batches. Might result in long SQL execution times otherwise.

# Optimization checklist

* [x] The changes are tested (migration works)
* [x] Number of queries is consistent
* [x] Memory usage is low
* [x] Memory usage does not increase between chunk iterations
* [x] Single query execution time is relatively low on large dataset (to be checked)

2022-02-23 17:00 UTC, patrys commented
Task linked: [SALEOR-6057 Optimize 0016_stock_quantity_allocated migration](https://app.clickup.com/t/2549495/SALEOR-6057)

2022-02-23 19:27 UTC, patrys commented on saleor/warehouse/migrations/0016_stock_quantity_allocated.py
> +        ids_to_update = stocks_ids[idx : idx + batch_size]  # noqa: E203
That is going to be very costly for the SQL server as it relies on offsets.

2022-02-23 19:43 UTC, patrys requested changes
Please use an approach that does not rely on offsets:

```python
last_id = 0

while True:
  stock_ids = list(Stock.objects.filter(id__gt=last_id).order_by('id').values_list('id', flat=True)[:batch_size])
  if not stock_ids:
    break
  last_id = stock_ids[-1]
  ...  # perform the update

2022-02-24 07:59 UTC, IKarbowiak commented on saleor/warehouse/migrations/0016_stock_quantity_allocated.py
> +                .values("allocations_allocated")[:1]
IMO, we should separate part for getting batches to another function, as it's hard to ready right now.

2022-02-24 08:46 UTC, IKarbowiak approved these changes

2022-02-24 09:07 UTC, korycins approved these changes

2022-02-24 09:38 UTC, maarcingebala approved these changes

2022-02-24 09:39 UTC, merged